package net.javaguides.banking.mapper;

import net.javaguides.banking.dto.AccountDto;
import net.javaguides.banking.entity.Account;

public class AccountMapper {
    
    // Method to map AccountDto to Account entity
    public static Account mapToAccount(AccountDto accountDto) {
        return new Account(
            accountDto.getId(),                // id will be generated by DB
            accountDto.getAccountHolderName(),  // Account holder's name
            accountDto.getBalance()             // Account balance
        );
    }

    // Method to map Account entity to AccountDto
    public static AccountDto mapToAccountDto(Account account) {
        return new AccountDto(
            account.getId(),
            account.getAccountHolderName(),
            account.getBalance()
        );
    }
}
